# Generated by Django 5.0.6 on 2026-06-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enroll', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='student/image')),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('python', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fsd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
