# Generated by Django 5.0.6 on 2026-06-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='coa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='python',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
