# Generated by Django 5.0.6 on 2026-06-25 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentdata_url_alter_studentdata_coa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('enroll', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='student/image')),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('url', models.URLField(blank=True)),
                ('python', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fsd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
